import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { InputTextProvider } from "@/providers/input-text-provider";
import { ReactFlowProvider } from "@xyflow/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ReactFlowProvider>
          <InputTextProvider>{children}</InputTextProvider>
        </ReactFlowProvider>
      </body>
    </html>
  );
}
